### ISSUE TITLE
Make order of operations significant

### ISSUE THREAD

**Issue by Myrdden** [korreman/sway-overfocus#12]
Hiya! Found this via that sway ticket & loving it, great work.

This request is probably going to seem esoteric but would it be possible to make the order in which the movement arguments were specified semantically significant?

My use case is essentially this (paraphrased):
```
bindsym [hjkl] exec sway-overfocus group-[ldur]w split-[ldur]w
bindsym Shift+[hjkl] exec sway-overfocus split-[ldur]w group-[ldur]w
```

So, because I have a layout that frequently ends up as alternations of tab > split > tab > sometimes split, what I'm after is for my basic hjkl movements to move group-wise if the focus is within a tabbed/stacked container, and split-wise if it's not (so, how it works currently). *However*, I would like, when I shift the keys, for the behaviour to be the exact opposite, where it will move *split-wise* when the focus is in a tabbed/stacked container, and *tab-wise* when it's in a split, which for me essentially has the effect of moving containers at the parent level instead of the focus level.

However, at the moment, unless I've set something up incorrectly, it would appear that both of those commands do the same thing, which I'd assume would mean the order of arguments is not taken into account.

**Comment by korreman** [comment]
> it would appear that both of those commands do the same thing, which I'd assume would mean the order of arguments is not taken into account.

Yep, the order of the targets is effectively disregarded. The command searches for the first matching parent of the focused window, so the ordering is overruled by the hierarchy in the tree. The only semantic ordering I can think of would be to search the entire focus path upward for a match to target 1, and if none was found, search for a match to target 2, etc.

But it sounds more like you need an intelligent version of `focus parent; focus <dir>`. Could you provide some example layouts and describe how the `Shift+[hjkl]` would work in these?

**Comment by Myrdden** [comment]
I suppose so, yeah, given the particular setup I have going on. And I guess in some other circumstances it would basically just be equivalent to the default direction commands. But then again, so is this repository, to some degree :D

I don't know how helpful this would be as an example, but before finding this project I'd been attempting (poorly) to do the same thing but just using bash and JQ, a JSON query language. I've gone and haphazardly taped sway-overfocus over my preexisting code in an attempt to replicate the behaviour, which looks like this:
```bash
layout=$(nodePath | jq -rcM '.[-2] | if type == "null" then empty else .layout end')
if [ "$layout" = 'splitv' ] || [ "$layout" = 'stacked' ]; then
	if [ "$2" = 'up' ]; then
		[ "$3" = 'super' ] \
			&& exec sway-overfocus "$([ "$layout" = 'tabbed' ] && echo 'split-us' || echo 'group-uw')" \
			|| exec sway-overfocus "$([ "$layout" = 'tabbed' ] && echo 'group-uw' || echo 'split-us')"
	elif [ "$2" = 'down' ]; then
		[ "$3" = 'super' ] \
			&& exec sway-overfocus "$([ "$layout" = 'tabbed' ] && echo 'split-ds' || echo 'group-dw')" \
			|| exec sway-overfocus "$([ "$layout" = 'tabbed' ] && echo 'group-dw' || echo 'split-ds')"
	elif [ "$2" = 'left' ]; then
		exec $0 focusParent
	elif [ "$2" = 'right' ]; then
		exec $0 focusChild
	fi
else
	if [ "$2" = 'up' ]; then
		exec $0 focusParent
	elif [ "$2" = 'down' ]; then
		exec $0 focusChild
	elif [ "$2" = 'left' ]; then
		[ "$3" = 'super' ] \
			&& exec sway-overfocus "$([ "$layout" = 'tabbed' ] && echo 'split-ls' || echo 'group-lw')" \
			|| exec sway-overfocus "$([ "$layout" = 'tabbed' ] && echo 'group-lw' || echo 'split-ls')"
	elif [ "$2" = 'right' ]; then
		[ "$3" = 'super' ] \
			&& exec sway-overfocus "$([ "$layout" = 'tabbed' ] && echo 'split-rs' || echo 'group-rw')" \
			|| exec sway-overfocus "$([ "$layout" = 'tabbed' ] && echo 'group-rw' || echo 'split-rs')"
	fi
fi
```
Which is certainly the most ridiculous possible way of accomplishing this, particularly given it's doing all of the work sway-overfocus does and then executing sway-overfocus to do it again. (I thought it might be helpful to try to provide an example within your codebase, but I'm going a bit cross-eyed having never actually read Rust before.)

The script is called with arguments à la sway, `focus {left|down|up|right} [super]`, where I've co-opted `super` to refer to the shifting behaviour I'm after. (Also, moving "perpendicularly" to the currently focused layout results in a focus parent/child, but that's irrelevant to this I think)

However it's occuring to me that one needn't repeatedly iterate the tree as I'm interpreting your description, it seems like it would suffice to filter the path from focus to root to the nearest of each available target and then select one from the result in the order the targets were specified, which I guess would only be a slightly longer iteration and one additional shorter one.

**Comment by Myrdden** [comment]
Right, so upon some further consideration I've realised that I'm so caught up in my own "implementation" of this functionality that I'm projecting it onto a project that's probably not actually meant to serve that same role.

Having tried it with the group and split movements actually separated, though, I'm finding I actually like that a lot more. So... I guess my solution comes in the form of just using the tool the way it was meant to :D You can feel free to close this, I suppose, if you don't think it's worth implementing something like this anyways.

**Comment by korreman** [comment]
Glad to hear that the current functionality ended up working for you as well. I can kinda see the idea of `Shift+hjkl` "doing the opposite". Though I think that the separated commands have the advantage of being more predictable and thus easier to commit to muscle memory.

If someone has a use case for ordered priority, feel free to open a new issue.
