### ISSUE TITLE
`swayipc` error: invalid integer, expected `i32`

### ISSUE THREAD

**Issue by c-dilks** [korreman/sway-overfocus#16]
I've been having a very sporadic issue where `sway-overfocus` will suddenly stop working; issuing any typical command in a shell returns:

```
$ sway-overfocus split-lt float-lt output-ls

swayipc error: invalid value: integer `4294967240`, expected i32 at line 1 column 9997
```

This problem persists for a while, then sporadically fixes itself, making it hard to test. Do you have any advice on what I could do to get more information when this happens again?

I got curious and looked through recent issues and PRs in [swayipc-rs](https://github.com/JayceFayne/swayipc-rs) and found a possible clue: [this PR](https://github.com/JayceFayne/swayipc-rs/pull/39) fixes a possibly [similar issue](https://github.com/greshake/i3status-rust/issues/1588) in `i3status`. Since `sway-overfocus` uses `swayipc` version 3.0.0, and as far as I can tell the aforementioned PR has not yet been included in a new tag of `swayipc`, I suppose asking the `swayipc` developers to tag a new release and push to crates.io would be a good idea; then the `swayipc` dependency could be updated here and hopefully this problem will be solved.

**Comment by korreman** [comment]
There are three places where `swayipc` can error in my program:

1. Starting a connection (unlikely).
2. Retrieving the tree.
3. Running the resulting focus command.

If you can reproduce the error, run `RUST_LOG=info sway-overfocus <...>` to figure out which it is.

Are you using i3? Looking at the last issue you mentioned, it might make sense to check whether your i3 version is up to date as well.

I'm a bit tied up with finishing my master's right now, but that'll be done in a week or so. I'll look into it then.

**Comment by korreman** [comment]
I almost forgot, `sway-overfocus` needs to be built in debug mode to enable logging. So you would run something like `RUST_LOG=info cargo run -- <...>` to get more info.

**Comment by c-dilks** [comment]
> If you can reproduce the error, run `RUST_LOG=info sway-overfocus <...>` to figure out which it is.
> I almost forgot, sway-overfocus needs to be built in debug mode to enable logging. So you would run something like RUST_LOG=info cargo run -- <...> to get more info.

Thanks! Now I hope it happens again...

> Are you using i3? Looking at the last issue you mentioned, it might make sense to check whether your i3 version is up to date as well.

Version 4.14.1, so I should probably update

**Comment by korreman** [comment]
In any case, the issue seems to be with `swayipc-rs` or `i3wm`. You can try upgrading i3, and if the problem reappears, nudging the `swayipc-rs` devs to make a patch release.
