### ISSUE TITLE
i3 compat dropped?

### ISSUE THREAD

**Issue by laur89** [korreman/sway-overfocus#17]
I suspect [this commit](https://github.com/korreman/sway-overfocus/commit/465bda6667398bdc48cf2440941f4799857e780e) drops i3 compatibility:

```sh
$ sway-overfocus split-rt float-rt output-rw
swayipc error: unknown variant `changed`, expected `fresh` or `none` at line 1 column 2380

$  i3 -v
i3 version 4661e74+ © 2009 Michael Stapelberg and contributors
```

Running sway-overfocus v0.2.4. Downgrading back to [sway-overfocus v0.2.3-fix](https://github.com/korreman/sway-overfocus/releases/tag/v0.2.3-fix) works fine.

Note i3 is built from [this commit](https://github.com/i3/i3/commit/4661e74b5ebe8727d1b0f8c29b1697f1f42daf70)

**Comment by korreman** [comment]
That's odd. Part of the reason for the upgrade was to get better compatibility with i3 from `swayipc-rs`.

Can you send the output of `i3-msg -t get_tree` when you get this error?

**Comment by korreman** [comment]
Seems likely to be https://github.com/JayceFayne/swayipc-rs/commit/2ef86da3b0f1448e0ecf5e5d55f3f7b2a5ca0ba7 missing a `changed` variant.

**Comment by laur89** [comment]
> Can you send the output of `i3-msg -t get_tree` when you get this error?

https://gist.github.com/laur89/d9d84d1bb7c40aa9f06a4b58ca4a5b80

**Comment by korreman** [comment]
Thanks! Try the latest commit, and see if it fixes the problem?

**Comment by laur89** [comment]
Yup, 5b03dca fixes it. Cheers!

**Comment by laur89** [comment]
@korreman could you please cut a tag+release including this fix?

**Comment by laur89** [comment]
@korreman ping... it's a minor, yet super-annoying issue

**Comment by korreman** [comment]
Putting it on my to-do for this weekend, sorry about the silence.
